# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rake'
gem 'minitest'
gem 'minitest-reporters', '~> 1.1', group: :test
